name: Get PR Comments

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fetch-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code for PR comments
        uses: actions/checkout@v2

      - name: Get PR comments
        run: |
          # Define variables
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.event.repository.name }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          
          # Use GitHub API to get all comments for the PR
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/comments" \
               -o pr_comments.json

      - name: Display PR comments
        run: |
          cat pr_comments.json
